2021-10-03 18:51:04,501 INFO    MainThread:273457 [internal.py:wandb_internal():89] W&B internal server running at pid: 273457, started at: 2021-10-03 18:51:04.501322
2021-10-03 18:51:04,503 DEBUG   HandlerThread:273457 [handler.py:handle_request():126] handle_request: check_version
2021-10-03 18:51:04,503 INFO    WriterThread:273457 [datastore.py:open_for_write():77] open: /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/NLP/Twitter-Sentiment-Analysis-V2/wandb/run-20211003_185103-2sjg0edz/run-2sjg0edz.wandb
2021-10-03 18:51:04,505 DEBUG   SenderThread:273457 [sender.py:send():182] send: header
2021-10-03 18:51:04,505 DEBUG   SenderThread:273457 [sender.py:send_request():196] send_request: check_version
2021-10-03 18:51:04,834 DEBUG   SenderThread:273457 [sender.py:send():182] send: run
2021-10-03 18:51:04,837 DEBUG   SenderThread:273457 [git.py:repo():33] git repository is invalid
2021-10-03 18:51:04,909 WARNING MainThread:273457 [internal.py:wandb_internal():145] Internal process interrupt: 1
2021-10-03 18:51:05,072 WARNING MainThread:273457 [internal.py:wandb_internal():145] Internal process interrupt: 2
2021-10-03 18:51:05,072 ERROR   MainThread:273457 [internal.py:wandb_internal():148] Internal process interrupted.
2021-10-03 18:51:05,336 INFO    SenderThread:273457 [dir_watcher.py:__init__():169] watching files in: /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/NLP/Twitter-Sentiment-Analysis-V2/wandb/run-20211003_185103-2sjg0edz/files
2021-10-03 18:51:05,336 INFO    SenderThread:273457 [sender.py:_start_run_threads():743] run started: 2sjg0edz with start time 1633267264
2021-10-03 18:51:05,337 INFO    SenderThread:273457 [sender.py:finish():979] shutting down sender
2021-10-03 18:51:05,337 INFO    SenderThread:273457 [dir_watcher.py:finish():283] shutting down directory watcher
2021-10-03 18:51:05,834 INFO    WriterThread:273457 [datastore.py:close():281] close: /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/NLP/Twitter-Sentiment-Analysis-V2/wandb/run-20211003_185103-2sjg0edz/run-2sjg0edz.wandb
2021-10-03 18:51:05,835 INFO    HandlerThread:273457 [handler.py:finish():683] shutting down handler
2021-10-03 18:51:06,337 INFO    SenderThread:273457 [dir_watcher.py:finish():313] scan: /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/NLP/Twitter-Sentiment-Analysis-V2/wandb/run-20211003_185103-2sjg0edz/files
2021-10-03 18:51:06,337 INFO    SenderThread:273457 [dir_watcher.py:finish():327] scan save: /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/NLP/Twitter-Sentiment-Analysis-V2/wandb/run-20211003_185103-2sjg0edz/files/config.yaml config.yaml
2021-10-03 18:51:06,337 INFO    SenderThread:273457 [file_pusher.py:finish():177] shutting down file pusher
2021-10-03 18:51:06,337 INFO    SenderThread:273457 [file_pusher.py:join():182] waiting for file pusher
2021-10-03 18:51:07,563 INFO    Thread-10 :273457 [upload_job.py:push():137] Uploaded file /home/indika/Programming/Projects/Python/Artifical-Intelligence/PyTorch/NLP/Twitter-Sentiment-Analysis-V2/wandb/run-20211003_185103-2sjg0edz/files/config.yaml
2021-10-03 18:51:08,288 INFO    MainThread:273457 [internal.py:handle_exit():76] Internal process exited
